# Generated by Django 6.0.5 on 2026-06-08 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('planned_route', models.JSONField(blank=True, default=dict)),
                ('actual_track', models.JSONField(blank=True, default=dict)),
                ('start_longitude', models.FloatField()),
                ('start_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('planned_distance_meters', models.FloatField(default=0.0)),
                ('walked_distance_meters', models.FloatField(default=0.0)),
                ('planned_ascent_meters', models.FloatField(default=0.0)),
                ('planned_descent_meters', models.FloatField(default=0.0)),
                ('walked_route_distance_meters', models.FloatField(default=0.0)),
                ('completion_ratio', models.FloatField(default=0.0)),
                ('deviation_count', models.PositiveIntegerField(default=0)),
                ('planned_moving_minutes', models.PositiveIntegerField(default=0)),
                ('planned_recommended_minutes', models.PositiveIntegerField(default=0)),
                ('actual_duration_seconds', models.PositiveIntegerField(default=0)),
                ('route_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
