# Generated by Django 6.0.5 on 2026-06-09 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_hikesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(default='gpx', max_length=32)),
                ('status', models.CharField(choices=[('canonical', 'Canonical'), ('merged', 'Merged')], default='canonical', max_length=16)),
                ('geometry', models.JSONField(default=dict)),
                ('original_gpx', models.TextField(blank=True)),
                ('distance_meters', models.FloatField(default=0.0)),
                ('ascent_meters', models.FloatField(default=0.0)),
                ('descent_meters', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_paths', to='maps.savedpath')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
